// src/scripts/process-data.ts
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import { parseLine, toZipCodeInfo, SECTION_SEPARATOR, LINE_SEPARATOR, FIELD_SEPARATOR } from "../loader.js"

// Get current file directory (needed for ES modules)
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Define paths
const sourceDataPath = path.join(__dirname, "..", "..", "data", "US.txt")
const outputJsPath = path.join(__dirname, "..", "..", "data", "zip-data.js")
const outputDtsPath = path.join(__dirname, "..", "..", "data", "zip-data.d.ts")

/**
 * Process the data file and generate a JavaScript module
 */
async function processData() {
  console.log("Processing ZIP code data file...")

  try {
    // Check if the source file exists
    if (!fs.existsSync(sourceDataPath)) {
      console.error(`Source data file not found: ${sourceDataPath}`)
      console.error(`Please download the US.txt file and place it in the data directory.`)
      process.exit(1)
    }

    // Make sure the output directory exists
    const outputDir = path.dirname(outputJsPath)
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true })
      console.log(`Created data directory: ${outputDir}`)
    }

    // Read the raw data file
    const fileContent = fs.readFileSync(sourceDataPath, "utf8")
    const lines = fileContent.split("\n")

    console.log(`Read ${lines.length} lines from data file`)

    // Process the data
    const processedData = []

    for (const line of lines) {
      if (!line.trim()) continue

      const rawData = parseLine(line)
      if (!rawData) continue

      // Only include US ZIP codes
      if (rawData.countryCode !== "US") continue

      processedData.push(toZipCodeInfo(rawData))
    }

    console.log(`Processed ${processedData.length} ZIP codes`)

    // Pack the data. Writing each record as its own object literal repeats the eight field names
    // 41,000 times over, and repeats every state, county and place name as often as it occurs -
    // which is what made this file 6.6 MB. Naming each one once and pointing at it by index brings
    // the same records, with the same values, down to 1.5 MB. See loader.ts for the format.
    const states: string[] = []
    const counties: string[] = []
    const places: string[] = []

    const seen = new Map<string[], Map<string, number>>()

    const indexOf = (table: string[], value: string): number => {
      let indexes = seen.get(table)

      if (!indexes) {
        indexes = new Map<string, number>()
        seen.set(table, indexes)
      }

      const existing = indexes.get(value)

      if (existing !== undefined) return existing

      const index = table.push(value) - 1
      indexes.set(value, index)

      return index
    }

    const entries = processedData.map((info) => {
      const fields = [
        info.zipCode,
        indexOf(places, info.placeName).toString(36),
        indexOf(states, [info.stateName, info.stateCode].join(FIELD_SEPARATOR)).toString(36),
        indexOf(counties, [info.countyName, info.countyCode].join(FIELD_SEPARATOR)).toString(36),
        String(info.latitude),
        String(info.longitude)
      ]

      // Only carry the optional fields on the records that have them
      if (info.communityName || info.communityCode) {
        fields.push(info.communityName ?? "", info.communityCode ?? "")
      }

      return fields.join(FIELD_SEPARATOR)
    })

    const packed = [
      states.join(LINE_SEPARATOR),
      counties.join(LINE_SEPARATOR),
      places.join(LINE_SEPARATOR),
      entries.join(LINE_SEPARATOR)
    ].join(SECTION_SEPARATOR)

    console.log(`Packed ${states.length} states, ${counties.length} counties, ${places.length} place names`)

    // A template literal so the tabs and newlines stay one byte each. No GeoNames field contains a
    // backtick, a backslash or a dollar sign, but escape them anyway so the file cannot be broken
    // by a future data update.
    const escaped = packed.replace(/[\\`]/g, "\\$&").replace(/\$\{/g, "\\${")

    const jsContent = `/**
 * Auto-generated ZIP code data file
 * DO NOT EDIT MANUALLY - Generated by process-data.ts
 */
export default \`${escaped}\`;
`

    fs.writeFileSync(outputJsPath, jsContent, "utf8")
    console.log(`Successfully wrote processed data to: ${outputJsPath}`)

    // Create a TypeScript declaration file
    const dtsContent = `declare const zipCodeData: string
export default zipCodeData
`

    fs.writeFileSync(outputDtsPath, dtsContent, "utf8")
    console.log(`Successfully wrote type declaration to: ${outputDtsPath}`)
  } catch (error) {
    console.error("Error processing ZIP code data:", error)
    process.exit(1)
  }
}

// Run the script
processData()
